server:
  port: 3000
  host: localhost

database:
  host: localhost
  port: 5432
  username: dev_user
  password: dev_password

app:
  name: Vanilla Node.js App
  version: 1.0.0
  environment: development
  debug: true
